#!/bin/sh

pip3 install --upgrade google-api-python-client
pip3 install --upgrade google-auth-httplib2
pip3 install --upgrade google-auth-oauthlib
pip3 install --upgrade termcolor 
pip3 install --upgrade jsonlib-python3
pip3 install --upgrade ics
pip3 install --upgrade icalendar